#!/bin/sh

# set correct gpg-agent settings
PATH_CFG="$HOME/.gnupg"
FILE_CFG="$PATH_CFG/gpg-agent.conf"
mkdir -p "$PATH_CFG"
if [ ! -f "$FILE_CFG" ]; then
    touch "$FILE_CFG"
fi

add_line() {
    STARTS_WITH=$(echo "$1" | awk '{print $1}')
    if grep "$1" -q <"$FILE_CFG"; then
        # already in file
        :
    else
        # is in file partially
        if grep "$STARTS_WITH" -q <"$FILE_CFG"; then
            echo "replacing '$STARTS_WITH' with: '$1'"
            sed -i "s|^$STARTS_WITH.*|$1|g" "$FILE_CFG"
        # is not in file
        else
            echo "adding: '$1'"
            echo "$1" >>"$FILE_CFG"
        fi
    fi
}

# add lines
add_line "pinentry-program /usr/bin/pinentry-curses"
add_line "auto-expand-secmem"
add_line "max-cache-ttl 1800"

# restart agent
echo "Reloading GPG-agent"
gpg-connect-agent reloadagent /bye || exit 1
